checking Accessibility of Portfolio Page
bhushan354/Portfolio_Project pull request #14
Opened 2023-06-18 13:24 UTC by bhushan354

2023-06-19 13:04 UTC, wayungi requested changes
Hi <STUDENT_MENTION>, 

![image](https://user-images.githubusercontent.com/99656687/234198503-c41d0396-d5b0-4466-8ed1-959de33796fa.png)


**Congratulations on the good job done so far!** 🤝 

There are some issues that you still need to work on to go to the next project but you are almost there! 😄 

## Highlights ⚡ ⚡ 
- [ ] Good commit messages ✔️ 
- [ ]  Correct GitHub flow ✔️ 
- [ ] Descriptive PR body ✔️ 

## Required Changes ♻️
_Check the comments under the review._
- [ ] Please make sure your headings are in a hierachy. Alos note that a page can only have one main heading `h1`. 
![titile](https://github.com/bhushan354/Portfolio_Project/assets/99656687/3ffe4d6c-f315-4d62-82ca-d3607ae5b52e)

- [ ] Your page has also failed the resize test. Your texts over lap when scale to 200%.
![resize](https://github.com/bhushan354/Portfolio_Project/assets/99656687/fa3a10c7-4f63-48c9-80a3-f22a445c0295)




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-20 17:59 UTC, bhushan354 commented
Hello sir , Thank you for giving your valuable review I have made changes as you suggested.

- Used only one h1 tag and also made all headings in hierarchy.

- Also fixed the resizing issue which was causing overlapping over text :
![Screenshot (54)](https://github.com/bhushan354/Portfolio_Project/assets/127464886/d2e145f7-f3d5-4056-909b-da75b9bb01a4)

Thank You,
Bhushan.

2023-06-20 18:52 UTC, KanzaTahreem requested changes
# Changes Required 🔁

Hi @bhushan354 🙋‍♀️

Good job so far! I really appreciate the effort you put in!  **_However, there are few this that still need to be fixed. But you are almost there!_** 💪 🏁

![so close](https://media.tenor.com/3sCHnD_x2RIAAAAC/almost-there.gif)


## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏

- ✅ Descriptive PR and README file
- ✅ Evaluated website's accessibility.
- ✅ Correct GitHub Flow

## Required Changes 🛑

_Please check the comments under the review._

## Optional suggestions ❕

N/A

Cheers and Happy coding!👏👨‍💻💻

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-20 18:52 UTC, KanzaTahreem commented on index.html
- [ ] As suggested previously, please make sure that you have only one `h1` per page and that should be the main headline. You can use `h2, h3, ...` for other heading but make sure that they are hierarchical such as mentioned below 👇 

```
Heading Level 1 <h1>
  Heading Level 2 <h2>
    Heading Level 3 <h3>
    Heading Level 3 <h3>
  Heading Level 2 <h2>
    Heading Level 3 <h3>
      Heading Level 4 <h4>
      Heading Level 4 <h4>
  Heading Level 2 <h2>
```
![image](https://github.com/bhushan354/Portfolio_Project/assets/106119105/439bc4a3-eb81-4b1d-aea1-f04c4a384b78)

2023-06-21 02:00 UTC, bhushan354 commented
Hello Kanza, Thank you for reviewing my code  I have made changes according to your review.

- Used only one h1 tag this time and used h2 tag for level 2 headings.

![image](https://github.com/bhushan354/Portfolio_Project/assets/127464886/e171031c-f203-47d0-ab3b-aa898993832b)

Thank you ,
Bhushan

2023-06-21 02:19 UTC, Shedrack-Sunday requested changes
Hi @bhushan354       👋

Congratulations! 🎉 Your project is complete and ready to be merged! 🚀

![image](https://i.pinimg.com/originals/3d/d2/07/3dd207237b39dcacd832f94a35428255.gif)


## Highlights
- Good job with the use of GitHub features✔️ 
- Kudos on implementing the changes as requested ✔️
 

## Optional Suggestions 💡
While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.
Cheers, and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread, and don't forget to tag me so I'll receive the notification.

As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-27 13:16 UTC, merged